// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkujwosaudvevtsuinwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdWp3b3NhdWR2ZXZ0c3VpbndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQ4NjUsImV4cCI6MjA2NTU3MDg2NX0.rFY-Kdh74ZB5kEY9qfX32cUGq-YqtGD7XV6M3A4Ltyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);